spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/techo
        username: techo
        password: abcd1234**
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update